[package]
name = "slier_minigrep"
description = "A mini program to search for specific word in provided file"
license = "MIT"
version = "0.1.0"
authors = ["slier81 <slier81@gmail.com>"]
edition = "2018"

[dependencies]
